 
#pragma warning( disable : 4996 ) 
 
#include <cstdlib>
#include <vector>
#include <iostream>
#include <string>
#include "G2D.h"
 

using namespace std;
  
 

struct Dessin {
    string roiBlanc =
        "[  K  KKKKKKK  K  ]"
        "[ KOKKRORRRORKKOK ]"
        "[ KOOROOOROOOROOK ]"
        "[ KOOOOOOOOOOOOOK ]"
        "[ KWAWAAWAWAAWAWK ]"
        "[ KOOOOOOOOOOOOOK ]"
        "[ KGTWDTTTTTDWTGK ]"
        "[ KGTWDTTTTTDWTGK ]"
        "[KGTTWWTTTTTWWTTGK]"
        "[KGTTTTGGGGGTTTTGK]"
        "[KGGGTGTTTTTGTGGGK]"
        "[ KGGTGTTGTTGTGGK ]"
        "[  KGGGGGGGGGGGK  ]"
        "[  KKGGGGGGGGGSK  ]"
        "[ Y KSSSSCSSSSKK  ]"
        "[YAY KKKSCSKKKWK  ]"
        "[ YKPWWWSCSWWWPK  ]"
        "[ GKPPPWSCSWPPPK  ]"
        "[ YPPPPWBCBWPPPK  ]"
        "[ G KPPWMMMWPPKK  ]"
        "[ G KPPWBCBWPPTK  ]"
        "[ G KPPWBCBWPPK   ]"
        "[ G KPPWBCBWPPK   ]"
        "[ G KPPWBCBWPPK   ]"
        "[ G KKKWBCBWKKK   ]"
        "[      KKKKK      ]";

    string roiNoir = "[  K  KKKKKKK  K  ]"
        "[ KYKKRYRRRYRKKYK ]"
        "[ KYYRYYYRYYYRYYK ]"
        "[ KYYYYYYYYYYYYYK ]"
        "[ KWAWAAWAWAAWAWK ]"
        "[ KYYYYYYYYYYYYYK ]"
        "[ KJTWRTTTTTRWTJK ]"
        "[ KJTWKTTTTTKWTJK ]"
        "[KJTTWWTTTTTWWTTJK]"
        "[KJTTTTJJJJJTTTTJK]"
        "[KJJJTJTTTTTJTJJJK]"
        "[ KJJTJTTJTTJTJJK ]"
        "[  KJJJJJJJJJJJK  ]"
        "[  KKJJJJJJJJJSK  ]"
        "[ Y KSSSSCSSSSKK  ]"
        "[YAY KKKSCSKKKWK  ]"
        "[ YKRWWWSCSWWWRK  ]"
        "[ GKRRRWSCSWRRRK  ]"
        "[ YRRRRWBCBWRRRK  ]"
        "[ G KRRWMMMWRRKK  ]"
        "[ G KRRWBCBWRRTK  ]"
        "[ G KRRWBCBWRRK   ]"
        "[ G KRRWBCBWRRK   ]"
        "[ G KRRWBCBWRRK   ]"
        "[ G KKKWBCBWKKK   ]"
        "[      KKKKK      ]";

    string reineBlanche =
        "[            U            ]"
        "[           UVU           ]"
        "[           UVU           ]"
        "[        YOUUUUUOY        ]"
        "[       OUUUUUUUUYO       ]"
        "[      OYOOOYYYYOYO       ]"
        "[      OYYOOOOYOOYYO      ]"
        "[      OYOTTTOOTTOYO      ]"
        "[     OYOTTTTTTTTTOYO     ]"
        "[     OYYTBWTTTWBWYYO     ]"
        "[     OYYTBBTTTBBWYYO     ]"
        "[      OYHHTTTTTHHYO      ]"
        "[     OYYOTTTTTTTOYYO     ]"
        "[    OYYYYOTTRRTOYYYYO    ]"
        "[   OYOWOOOOTTTOOOOWOYO   ]"
        "[   OYOWWWTTTTTTTWWWOYO   ]"
        "[  OYYOOXWWWWTWWWWXOOYYO  ]"
        "[  OYOXXXIWWWWWWWIXXXOYO  ]"
        "[   OXXXXIIIIWIIIIXXXXO   ]"
        "[    XXXOIIIIIIIIIOXXX    ]"
        "[   XXXOYOIIIIIIIOYOXXX   ]"
        "[  XXXOYYOIIIIIIIOYYOXXX  ]"
        "[ TTT  OO HIIIIIH OO  TTT ]"
        "[ TTT    HHHIIIHHH    TTT ]"
        "[       HHHHHIHHHHH       ]"
        "[       HHXHHHHHXHH       ]"
        "[      HHXXXHHHXXXHH      ]"
        "[      HZXXXXHXXXXZH      ]"
        "[      HZXXXZHZXXXZH      ]"
        "[      ZXXXZXXXZXXXZ      ]"
        "[      ZXXXZXXXZXXXZ      ]"
        "[     ZXXXZXXXXXZXXXZ     ]"
        "[    ZXXXXZXXXXXZXXXXZ    ]"
        "[    ZXXXXZXXXXXZXXXXZ    ]"
        "[   ZXXXXZXXXXXXXZXXXXZ   ]"
        "[   ZXXXXZXXXXXXXZXXXXZ   ]"
        "[  ZXXXXZXXXXXXXXXZXXXXZ  ]"
        "[ ZXXXXZXXXXXXXXXXXZXXXXZ ]"
        "[ ZXXXZXXXXXXXXXXXXXZXXXZ ]"
        "[ZXXXZXXXXXXXXXXXXXXXZXXXZ]"
        "[ZXXZXXXXXXXXXXXXXXXXXZXXZ]"
        "[ ZXZXXXXXXXXXXXXXXXXXZXZ ]"
        "[  ZZZZZXXXXXXXXXXXZZZZZ  ]"
        "[       ZZZZZZZZZZZ       ]"; 

    string reineNoire =
        "[            U            ]"
        "[           UVU           ]"
        "[           UVU           ]"
        "[        LFUUUUUFL        ]"
        "[       FUUUUUUUULF       ]"
        "[      FLFFFLLLLFLF       ]"
        "[      FLLFFFFLFFLLF      ]"
        "[      FLFTTTFFTTFLF      ]"
        "[     FLFTTTTTTTTTFLF     ]"
        "[     FLLTQVTTTVQTLLF     ]"
        "[     FLLTQQTTTQQTLLF     ]"
        "[      FLCCTTTTTCCLF      ]"
        "[     FLLFTTTTTTTFLLF     ]"
        "[    FLLLLFTTRRTFLLLLF    ]"
        "[   FLFWFFFFTTTFFFFWFLF   ]"
        "[   FLFWWWTTTTTTTWWWFLF   ]"
        "[  FLLFFNWWWWTWWWWNFFLLF  ]"
        "[  FLFNNNEWWWWWWWENNNFLF  ]"
        "[   FNNNNEEEEWEEEENNNNF   ]"
        "[    NNNFEEEEEEEEEFNNN    ]"
        "[   NNNFLFEEEEEEEFLFNNN   ]"
        "[  NNNFLLFEEEEEEEFLLFNNN  ]"
        "[ TTT  FF CEEEEEC FF  TTT ]"
        "[ TTT    CCCEEECCC    TTT ]"
        "[       CCCCCECCCCC       ]"
        "[       CCNCCCCCNCC       ]"
        "[      CCNNNCCCNNNCC      ]"
        "[      CBNNNNCNNNNBC      ]"
        "[      CBNNNBCBNNNBC      ]"
        "[      BNNNBNNNBNNNB      ]"
        "[      BNNNBNNNBNNNB      ]"
        "[     BNNNBNNNNNBNNNB     ]"
        "[    BNNNNBNNNNNBNNNNB    ]"
        "[    BNNNNBNNNNNBNNNNB    ]"
        "[   BNNNNBNNNNNNNBNNNNB   ]"
        "[   BNNNNBNNNNNNNBNNNNB   ]"
        "[  BNNNNBNNNNNNNNNBNNNNB  ]"
        "[ BNNNNBNNNNNNNNNNNBNNNNB ]"
        "[ BNNNBNNNNNNNNNNNNNBNNNB ]"
        "[BNNNBNNNNNNNNNNNNNNNBNNNB]"
        "[BNNBNNNNNNNNNNNNNNNNNBNNB]"
        "[ BNBNNNNNNNNNNNNNNNNNBNB ]"
        "[  BBBBBNNNNNNNNNNNBBBBB  ]"
        "[       BBBBBBBBBBB       ]";
    string ChevalierNoir =

        "[                       KKKKK                ]"
        "[                      KJ!!!JK               ]"
        "[                     KJ!!J!!JK              ]"
        "[                     KJ!JTJ!JK              ]"
        "[                      KJTB!JJK              ]"
        "[                      KTTB!TTK              ]"
        "[                      KTTTTTKK              ]"
        "[                    KKKKTTTKKKKK            ]"
        "[                   KNKKKKKKEEKNEK           ]"
        "[                   KKE?EEE??KNOJJK          ]"
        "[                  KOK?NNNN??KNO!JK          ]"
        "[                 KO?K?NNNN??KN?O!JK         ]"
        "[                 KNEKEKKKKKKKKN?O!EK        ]"
        "[      KKKKKKK     KKKKE?N??EKKKK??KK        ]"
        "[    KK!!!!!!!KK  K?O!KE?N??EK KEKKK         ]"
        "[   K!!!*!!*!!!*KK?K?EKE?N??EK  KO!KK        ]"
        "[  K*!****!**!**JK??KK K????EKK K?K?EK       ]"
        "[ KK**JKKJ*****JJJK?K K????EEEEKKKK?EK       ]"
        "[KF!OOK/FJ*JJ*JJ*JJKK KKKKKKEN?*K?EKKKK      ]"
        "[ KKNNOKKKJJJJJJ*JJJJK!KKKKKEKK?KKKEK*JK     ]"
        "[  KN?EG!!JKFJFJJJJJKKK!KKKKKOOKNKKKK***K    ]"
        "[  KN?E!JE!KF//JFFJJFFK!KKKSSKOK???EKK***K   ]"
        "[  K??E!K?EKFF//F/JF/FJ!SSS+WKOOK?EKEEK**K   ]"
        "[   KOOOK?K//FF////F/SSS+WWW++KGKKKNNEEKJJK  ]"
        "[   KNE!FEK///FF//SSS+WWW++GSS?KK?N?EEEEKJK  ]"
        "[   K?E!KK1F//FSSS+WWW++GSSSN?KK?NGGG!!EKJK  ]"
        "[   KE/FFK11FSS+WWW++GSSSFKNNN?EKGGG!!EEKJK  ]"
        "[   K/KF1K11S+WW++GSSSFJJJJKEEEKKEE!!EEEKK   ]"
        "[    KKKKKKSWW+GSSS/JJJ!**!KKKKEK?NEE?EEKK   ]"
        "[        KKSSSSSKKKJ!!*JJJ!JK?EEK????EEKJK   ]"
        "[        K??N???EEK*JJJFFJ!JK??EEKEEEEKKJK   ]"
        "[        KGGN?G!!EKJFFF/FJ*KKE?EEKKKKKKJJJK  ]"
        "[       K1K?GG!EEKFF///FJJ*KE?EEEKF//FKJJJK  ]"
        "[      K111KN??KKFF///FFJ*JK?N??EKFF/FKJJJJK ]"
        "[     K11111KKKF11FFFFFJKKKKNNN?K/FFFFKJJJJJK]"
        "[     KFFKKKKKKKKKKFFFKK   KKKKKKK/FFFFKJJJJK]"
        "[     KFFK        KFFFK      K111KKKFF//KJKK ]"
        "[     K111KKK      KFFK      K111K1FKF//KK   ]"
        "[      KK11KSK     KFFK      K11K  1FKFFK    ]"
        "[       K111SK     K//FK    K111K   1KFFK    ]"
        "[        KKSSK     K//FK    K111K    KFFK    ]"
        "[          KK       KF1K   K1111K    KFFK    ]"
        "[                   KF1KKK KSS1K    KFFFK    ]"
        "[            KKKKKKKKF1KKKKKSSSKKKKKKFFFKKK  ]"
        "[        KKKKKKKKKKKKFFFKKKKKKKKKKKKFFFKKKK  ]"
        "[       KKKKKKKKKKKKFGGKKKKKKKKKKKKKSSSKKK   ]"
        "[       KKKKKKKKKKKKSSGFKKKKKKKKKKKKSSSKKK   ]"
        "[        KKKKKKKKKKKSSSKKKKKKKKKKKKKKKKK     ]"
        "[             KKKKKKKKKKKKKKKK               ]";
};
 